export const latestMigrationName = "000011_issuance_quota_retention";

export const requiredDatabaseRelations = Object.freeze([
  "public.loop_users",
  "public.provider_operations",
  "public.idempotency_records",
  "public.audit_events",
  "public.issuance_rate_records",
  "public.perp_intents",
  "public.perp_intent_items",
  "public.perp_intent_events",
  "public.perp_wallet_bindings",
  "public.perp_wallet_binding_events",
  "public.spot_agent_identities",
  "public.spot_agent_identity_events",
  "public.spot_intents",
  "public.spot_intent_events",
  "public.spot_agent_authorizations",
  "public.spot_agent_authorization_events",
  "public.hyperliquid_signer_nonce_state",
  "public.hyperliquid_signer_nonce_allocations",
  "public.perp_agent_identities",
  "public.perp_agent_authorizations",
  "public.perp_agent_authorization_events",
  "public.user_profiles",
  "public.privacy_preferences",
  "public.watchlist_versions",
  "public.watchlist_groups",
  "public.watchlist_items",
  "public.price_alert_definitions",
  "public.notification_preference_versions",
  "public.notification_preferences",
  "public.price_alert_events",
] as const);
