/** Inventory is explicit about readiness. No arbitrary key/value editor: every
 * writable setting must have a validated consumer and dedicated permission. */
export const opsCatalog = [
  {
    module: "挖矿",
    name: "公式、资产权重、社区系数、价格规则",
    status: "connected",
    consumer: "mining snapshot worker",
    entry: "drafts",
  },
  {
    module: "挖矿",
    name: "版本批准并发布、历史快照撤回",
    status: "connected",
    consumer: "mining_formula_versions / mining_snapshots",
    entry: "mining",
  },
  {
    module: "社区",
    name: "申请审核、拒绝理由",
    status: "connected",
    consumer: "community detail / official channel / notification feed",
    entry: "communities",
  },
  {
    module: "客服",
    name: "工单回复、关闭",
    status: "connected",
    consumer: "owner-scoped support ticket events",
    entry: "support",
  },
  {
    module: "社区",
    name: "管理员、转让、禁言与封禁",
    status: "app",
    consumer: "community member actions",
    entry: null,
  },
  {
    module: "群聊",
    name: "普通群资料、成员、角色、邀请管理",
    status: "contract_pending",
    consumer: "Stream group service",
    entry: null,
  },
  {
    module: "项目",
    name: "审核、里程碑、白名单计算、销售登记",
    status: "script",
    consumer: "launch review and allowlist scripts",
    entry: null,
  },
  {
    module: "资产",
    name: "代币与池登记",
    status: "script",
    consumer: "registry scripts and chain metadata",
    entry: null,
  },
  {
    module: "推荐",
    name: "社区顺序、默认推荐、上下架",
    status: "contract_pending",
    consumer: "community recommendation",
    entry: null,
  },
  {
    module: "内容",
    name: "活动、公告、举报处置",
    status: "contract_pending",
    consumer: "scoped content resources",
    entry: null,
  },
  {
    module: "邀请",
    name: "五级加成及资格规则",
    status: "contract_pending",
    consumer: "mining referral calculation pending",
    entry: null,
  },
  {
    module: "客户端",
    name: "最低版本、强更、商店地址、条款版本",
    status: "deployment",
    consumer: "client policy / terms",
    entry: null,
  },
  {
    module: "用户",
    name: "用户名禁用词",
    status: "deployment",
    consumer: "alias validation",
    entry: null,
  },
  {
    module: "客服",
    name: "响应时限、工作日口径",
    status: "code_policy",
    consumer: "supportResponsePolicy",
    entry: null,
  },
  {
    module: "行情",
    name: "热门榜排序与数量",
    status: "code_policy",
    consumer: "marketTrendingRules",
    entry: null,
  },
  {
    module: "AI",
    name: "模型、用户及社区配额、输出上限、缓存",
    status: "deployment",
    consumer: "community AI service",
    entry: null,
  },
  {
    module: "AI",
    name: "知识文档导入、撤回与授权",
    status: "contract_pending",
    consumer: "document retrieval pending",
    entry: null,
  },
  {
    module: "交易",
    name: "滑点、价格影响、TTL、费用、gas 预留",
    status: "confirmation_required",
    consumer: "swap policy pendingProductConfirmation",
    entry: null,
  },
  {
    module: "运维",
    name: "频道上限、索引回填、频道修复",
    status: "restricted",
    consumer: "technical operations only",
    entry: null,
  },
  {
    module: "合约",
    name: "税率、矿池预算、链上白名单与资金执行",
    status: "handoff_only",
    consumer: "contract handoff",
    entry: null,
  },
] as const;
