import { randomInt } from "node:crypto";

/**
 * Decision 0055: the server-generated persona shown for a member inside one
 * official community channel. The alias is `<Word>-<4 digits>`: a neutral
 * English word from the compiled list below plus four uniformly random
 * digits. It never contains a brand, a product name, the member's public
 * alias, or any fragment of an internal, Privy, or Stream identifier, so it
 * cannot be correlated across communities.
 *
 * The generator is stateless; uniqueness inside a community is enforced by
 * the `community_channel_personas_alias_unique` constraint, and the
 * repository retries a collision with a fresh draw.
 */

export const communityPersonaAliasVersion = 1 as const;

export const communityPersonaAliasPatternSource = "^[A-Z][a-z]{2,15}-[0-9]{4}$";
const communityPersonaAliasPattern = new RegExp(
  communityPersonaAliasPatternSource,
);

export const communityPersonaWords: readonly string[] = Object.freeze([
  "Acorn",
  "Alder",
  "Amber",
  "Amethyst",
  "Anchor",
  "Antler",
  "Apricot",
  "Arbor",
  "Arrow",
  "Ash",
  "Aspen",
  "Aster",
  "Atlas",
  "Auburn",
  "Aurora",
  "Avalanche",
  "Badger",
  "Balsam",
  "Bamboo",
  "Banner",
  "Barley",
  "Basil",
  "Bay",
  "Beacon",
  "Beech",
  "Bell",
  "Birch",
  "Bison",
  "Blossom",
  "Boulder",
  "Bramble",
  "Brass",
  "Breeze",
  "Brook",
  "Cactus",
  "Canyon",
  "Caravan",
  "Cardinal",
  "Cedar",
  "Cello",
  "Chalk",
  "Chestnut",
  "Cinder",
  "Citrus",
  "Cliff",
  "Cloud",
  "Clover",
  "Cobalt",
  "Cocoa",
  "Comet",
  "Compass",
  "Condor",
  "Copper",
  "Coral",
  "Cosmos",
  "Cove",
  "Crane",
  "Creek",
  "Crest",
  "Cricket",
  "Crystal",
  "Cypress",
  "Dahlia",
  "Daisy",
  "Dew",
  "Dolphin",
  "Dragonfly",
  "Driftwood",
  "Dune",
  "Dusk",
  "Eagle",
  "Echo",
  "Elk",
  "Elm",
  "Ember",
  "Falcon",
  "Fennel",
  "Fern",
  "Fig",
  "Finch",
  "Firefly",
  "Fjord",
  "Flint",
  "Forest",
  "Fossil",
  "Fox",
  "Frost",
  "Galaxy",
  "Garnet",
  "Gazelle",
  "Ginger",
  "Glacier",
  "Glade",
  "Glow",
  "Granite",
  "Grove",
  "Gull",
  "Harbor",
  "Harvest",
  "Hawk",
  "Hazel",
  "Heather",
  "Heron",
  "Hickory",
  "Hollow",
  "Horizon",
  "Ibis",
  "Iris",
  "Island",
  "Ivory",
  "Ivy",
  "Jade",
  "Jasmine",
  "Jasper",
  "Jetty",
  "Juniper",
  "Kelp",
  "Kestrel",
  "Koala",
  "Lagoon",
  "Lantern",
  "Larch",
  "Lark",
  "Lava",
  "Lemon",
  "Lichen",
  "Lilac",
  "Lily",
  "Linden",
  "Lotus",
  "Lynx",
  "Magnet",
  "Manatee",
  "Maple",
  "Marble",
  "Marigold",
  "Marsh",
  "Meadow",
  "Mesa",
  "Meteor",
  "Mint",
  "Mist",
  "Moss",
  "Mulberry",
  "Narwhal",
  "Nebula",
  "Nectar",
  "Nettle",
  "Nimbus",
  "Nutmeg",
  "Oak",
  "Oasis",
  "Ocean",
  "Olive",
  "Onyx",
  "Opal",
  "Orchid",
  "Oriole",
  "Osprey",
  "Otter",
  "Owl",
  "Palm",
  "Panda",
  "Papaya",
  "Parrot",
  "Pearl",
  "Pebble",
  "Pelican",
  "Peony",
  "Pepper",
  "Pine",
  "Pinecone",
  "Plover",
  "Plum",
  "Pollen",
  "Poplar",
  "Prairie",
  "Prism",
  "Puffin",
  "Pumpkin",
  "Quail",
  "Quartz",
  "Quill",
  "Rain",
  "Raven",
  "Redwood",
  "Reed",
  "Ridge",
  "Ripple",
  "River",
  "Robin",
  "Rosemary",
  "Rowan",
  "Ruby",
  "Saddle",
  "Saffron",
  "Sage",
  "Sail",
  "Salmon",
  "Sand",
  "Sapphire",
  "Seal",
  "Sequoia",
  "Shadow",
  "Shore",
  "Silver",
  "Slate",
  "Snow",
  "Sorrel",
  "Sparrow",
  "Spring",
  "Spruce",
  "Starling",
  "Stone",
  "Storm",
  "Summit",
  "Sunflower",
  "Swan",
  "Sycamore",
  "Tamarind",
  "Tangerine",
  "Teal",
  "Tern",
  "Thistle",
  "Thunder",
  "Thyme",
  "Timber",
  "Topaz",
  "Toucan",
  "Trail",
  "Trout",
  "Tulip",
  "Tundra",
  "Umber",
  "Valley",
  "Vanilla",
  "Velvet",
  "Violet",
  "Walnut",
  "Walrus",
  "Wave",
  "Wheat",
  "Willow",
  "Wind",
  "Wren",
  "Yarrow",
  "Yew",
  "Zebra",
  "Zenith",
  "Zephyr",
  "Zinc",
]);

/**
 * Uniform integer in `[0, exclusiveMaximum)`. Tests inject a deterministic
 * source; production uses `crypto.randomInt`.
 */
export type PersonaRandomSource = (exclusiveMaximum: number) => number;

const defaultRandomSource: PersonaRandomSource = (exclusiveMaximum) =>
  randomInt(exclusiveMaximum);

export function isCommunityPersonaAlias(value: unknown): value is string {
  return typeof value === "string" && communityPersonaAliasPattern.test(value);
}

export function generateCommunityPersonaAlias(
  random: PersonaRandomSource = defaultRandomSource,
): string {
  const wordIndex = random(communityPersonaWords.length);
  const word = communityPersonaWords[wordIndex];
  const digits = random(10_000);
  if (
    word === undefined ||
    !Number.isInteger(digits) ||
    digits < 0 ||
    digits >= 10_000
  ) {
    throw new Error("The persona random source is out of range");
  }
  const alias = `${word}-${String(digits).padStart(4, "0")}`;
  if (!isCommunityPersonaAlias(alias)) {
    throw new Error("The generated persona alias is malformed");
  }
  return alias;
}

export function createCommunityPersonaAliasGenerator(
  random: PersonaRandomSource = defaultRandomSource,
): () => string {
  return () => generateCommunityPersonaAlias(random);
}
